### ISSUE TITLE
Why does canexport() for alphashape return false?

### ISSUE THREAD

**Issue by anitagraser** [sanak/pgRoutingLayer#2]
Is there a specific reason why alphashapes cannot be exported? Have you tried and run into a problem? I'd like to know because I was thinking of trying to implement it.

**Comment by sanak** [comment]
@anitagraser
I supported this at https://github.com/pgRouting/pgRoutingLayer/commit/404d5d1883f3885d0202c6caf58ec2ad71f31248 commit by using PostgreSQL `WITH` query.
(But, I don't modify "Export merged" function yet.)

I am planning to support new pgRouting v2.1.0 soon (at September 2015), but is it better for me to send pull request (pgRouting@`pgr-2.0_improvement` branch), once ?

**Comment by anitagraser** [comment]
Hi Ko,
Great to hear that you are planning to add further improvements! I've just given you push access to the   main repository. Please feel free to add features as you set fit.
Best wishes,
Anita

**Comment by sanak** [comment]
Okay, thanks!

**Comment by sanak** [comment]
Sorry for too old topic, but I supported this in the following commit, so I close this issue.
https://github.com/pgRouting/pgRoutingLayer/commit/404d5d1883f3885d0202c6caf58ec2ad71f31248
Thanks!
